import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { parseDocument } from 'yaml';

async function workflow(name) {
  const path = `.github/workflows/${name}.yml`;
  assert.ok(existsSync(path), `${name} workflow is required`);
  const document = parseDocument(await readFile(path, 'utf8'), { uniqueKeys: true });
  assert.deepEqual(document.errors, [], `${name} must be valid, unambiguous YAML`);
  return document.toJS();
}

function assertVerifyJob(job) {
  assert.equal(job['runs-on'], 'ubuntu-latest');
  const setup = job.steps.find(step => step.uses?.startsWith('actions/setup-node@'));
  assert.equal(String(setup.with['node-version']), '22');
  assert.equal(setup.with.cache, 'npm');
  const commands = job.steps.filter(step => step.run).map(step => step.run);
  assert.deepEqual(commands, ['npm ci', 'npx playwright install --with-deps chromium', 'npm run verify']);
  const debug = job.steps.find(step => step.name === 'Preserve failing browser evidence');
  assert.ok(debug?.uses?.startsWith('actions/upload-artifact@'));
  assert.equal(debug.if, 'failure()');
  assert.ok(debug.with.path.includes('playwright-report/'));
  assert.ok(debug.with.path.includes('test-results/'));
  assert.equal(job['continue-on-error'], undefined);
  for (const step of job.steps) assert.equal(step['continue-on-error'], undefined);
}

test('every branch push and PR executes the same complete non-production gate with read-only repository access', async () => {
  const ci = await workflow('ci');
  assert.equal(ci.on.push, null, 'non-production CI must run on every pushed feature branch before main integration');
  assert.ok(Object.hasOwn(ci.on, 'pull_request'));
  assert.deepEqual(ci.permissions, { contents: 'read' });
  assertVerifyJob(ci.jobs.verify);
  const { scripts } = JSON.parse(await readFile('package.json', 'utf8'));
  assert.deepEqual(scripts.verify.split(' && '), [
    'npm run typecheck', 'npm run test:typecheck', 'npm run lint', 'npm test -- --run',
    'npm run build', 'npm run test:delivery', 'npm run test:e2e',
  ]);
});

test('successful CI preserves native-size fidelity captures at paths produced by Playwright', async () => {
  const ci = await workflow('ci');
  const upload = ci.jobs.verify.steps.find(step => step.name === 'Preserve successful fidelity screenshots');
  assert.ok(upload?.uses?.startsWith('actions/upload-artifact@'));
  assert.equal(upload.if, 'success()');
  assert.equal(upload.with['if-no-files-found'], 'error');
  const paths = upload.with.path.trim().split(/\s*\n\s*/);
  const expectedNames = [
    'desktop-command-center-1586x992.png',
    'mobile-assessment-390x844.png',
    'mobile-assessment-430x764.png',
  ];
  assert.deepEqual(paths, expectedNames.map(name => `test-results/**/${name}`));
  const fidelitySpec = await readFile('e2e/fidelity.spec.ts', 'utf8');
  for (const name of expectedNames) assert.ok(fidelitySpec.includes(name), `${name} must be generated by the successful fidelity test`);
  assert.match(await readFile('playwright.config.ts', 'utf8'), /preserveOutput:\s*['"]always['"]/);
  const verify = ci.jobs.verify.steps.findIndex(step => step.run === 'npm run verify');
  assert.ok(ci.jobs.verify.steps.indexOf(upload) > verify, 'screenshots can be uploaded only after the complete browser gate passes');
});

test('Pages can deploy only the artifact verified in the same successful main-push workflow', async () => {
  const pages = await workflow('deploy-pages');
  assert.deepEqual(pages.on, { push: { branches: ['main'] } });
  assert.deepEqual(pages.permissions, { contents: 'read' });
  assertVerifyJob(pages.jobs.verify);
  const steps = pages.jobs.verify.steps;
  const upload = steps.findIndex(step => step.uses?.startsWith('actions/upload-pages-artifact@'));
  assert.ok(upload > steps.findIndex(step => step.run === 'npm run verify'));
  assert.equal(steps[upload].with.path, 'dist');
  assert.ok(!steps[upload].if || steps[upload].if === 'success()');
  const deploy = pages.jobs.deploy;
  assert.equal(deploy.needs, 'verify');
  assert.equal(deploy.if, undefined, 'deploy must retain the default success-only dependency gate');
  assert.deepEqual(deploy.permissions, { pages: 'write', 'id-token': 'write' });
  assert.deepEqual(deploy.environment, { name: 'github-pages', url: 'https://yht5582-source.github.io/SA-AKI/' });
  const configure = deploy.steps.find(step => step.uses?.startsWith('actions/configure-pages@'));
  assert.equal(configure?.with?.enablement, true, 'the first verified deployment must be able to enable the Pages site');
  assert.ok(deploy.steps.some(step => step.uses?.startsWith('actions/deploy-pages@')));
  assert.ok(!deploy.steps.some(step => step.uses?.startsWith('actions/download-artifact@')));
});
